<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SphinxClient' => $vendorDir . '/neutron/sphinxsearch-api/sphinxapi.php',
    'getID3' => $vendorDir . '/james-heinrich/getid3/getid3/getid3.php',
    'getid3_exception' => $vendorDir . '/james-heinrich/getid3/getid3/getid3.php',
    'getid3_handler' => $vendorDir . '/james-heinrich/getid3/getid3/getid3.php',
);
