<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'OAuth\\Unit' => array($vendorDir . '/lusitanian/oauth/tests'),
    'OAuth' => array($vendorDir . '/lusitanian/oauth/src'),
    'JasonGrimes' => array($vendorDir . '/jasongrimes/paginator/src'),
    'Discogs' => array($vendorDir . '/ricbra/php-discogs-api/lib'),
    'ComponentInstaller' => array($vendorDir . '/robloach/component-installer/src'),
    'ColorThief' => array($vendorDir . '/ksubileau/color-thief-php/lib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
