<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'JasonGrimes' => array($vendorDir . '/jasongrimes/paginator/src'),
    'Discogs' => array($vendorDir . '/ricbra/php-discogs-api/lib'),
    'ComponentInstaller' => array($vendorDir . '/robloach/component-installer/src'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
