<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AbstractController' => $vendorDir . '/mmp/mmp/lib/AbstractController.class.php',
    'AbstractMigration' => $vendorDir . '/mmp/mmp/lib/AbstractMigration.class.php',
    'AbstractSchema' => $vendorDir . '/mmp/mmp/lib/AbstractSchema.class.php',
    'Attribute' => $vendorDir . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'GetOpt' => $vendorDir . '/mmp/mmp/lib/GetOpt.class.php',
    'Helper' => $vendorDir . '/mmp/mmp/lib/Helper.class.php',
    'Normalizer' => $vendorDir . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    'Output' => $vendorDir . '/mmp/mmp/lib/Output.class.php',
    'PhpToken' => $vendorDir . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
    'SphinxClient' => $vendorDir . '/neutron/sphinxsearch-api/sphinxapi.php',
    'Stringable' => $vendorDir . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
    'UnhandledMatchError' => $vendorDir . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
    'ValueError' => $vendorDir . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
    'addController' => $vendorDir . '/mmp/mmp/lib/addController.class.php',
    'createController' => $vendorDir . '/mmp/mmp/lib/createController.class.php',
    'dbDiff' => $vendorDir . '/mmp/mmp/lib/dbDiff.class.php',
    'helpController' => $vendorDir . '/mmp/mmp/lib/helpController.class.php',
    'initController' => $vendorDir . '/mmp/mmp/lib/initController.class.php',
    'listController' => $vendorDir . '/mmp/mmp/lib/listController.class.php',
    'migrateController' => $vendorDir . '/mmp/mmp/lib/migrateController.class.php',
    'schemaController' => $vendorDir . '/mmp/mmp/lib/schemaController.class.php',
);
