<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '82cd75ac285fe70e0a85db7f41ded7e6075c9419',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '82cd75ac285fe70e0a85db7f41ded7e6075c9419',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ajjahn/puppet-mpd' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ajjahn/puppet-mpd',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => 'v0.11.x-dev',
            'version' => '0.11.9999999.9999999-dev',
            'reference' => '8d60a347dd96c2c748f8993300a27d079a53144a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bryanjhv/slim-session' => array(
            'pretty_version' => '3.7.2',
            'version' => '3.7.2.0',
            'reference' => '4820d38467bb4e2896f893e3a1bef695f1729568',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bryanjhv/slim-session',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codrops/bookblock' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codrops/bookblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/backbone' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '478a3769d64bf8d3e8798558f01b16c1e160d670',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/backbone',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/font-awesome' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => '885308b939369d147bec93174722786bc2c4eedd',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/font-awesome',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/jquery' => array(
            'pretty_version' => '2.2.x-dev',
            'version' => '2.2.9999999.9999999-dev',
            'reference' => '981036fcb56668433a7eb0d1e71190324b4574df',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/jquery-cookie' => array(
            'pretty_version' => '1.4.1.2',
            'version' => '1.4.1.2',
            'reference' => '0a10666155fd3aab9be5735b0ba83a4dccf59d78',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/jquery-cookie',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/jqueryui' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'reference' => '44ecf3794cc56b65954cc19737234a3119d036cc',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/jqueryui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'components/underscore' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '91142c898763ca8bb23a32a9808735e4998839d1',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/underscore',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.1.x-dev',
            'version' => '2.1.9999999.9999999-dev',
            'reference' => 'bf265da9f831e46e646c7a01b59ee8a33f8c0365',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'forsigner/magic-check' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../forsigner/magic-check',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'greensock/greensock-js' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../greensock/greensock-js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/command' => array(
            'pretty_version' => '0.7.1',
            'version' => '0.7.1.0',
            'reference' => '2e8286ff81f75f97b00f7dcc2f51e2efafb373bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/command',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '5.3.x-dev',
            'version' => '5.3.9999999.9999999-dev',
            'reference' => 'd59d5293b4a804d6436d64fec71a8c75110a3165',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle-services' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'reference' => '5402867628d266748db88f05c90ede54fd1d884c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle-services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/oauth-subscriber' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => '03f1ebe31d3112526106d0570c80eba6820e86e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/oauth-subscriber',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5e2a174052995663dd68e6b5ad838afd47dd615b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/ringphp',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'guzzlehttp/streams' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'd99a261c616210618ab94fd319cb17eda458cc3e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/streams',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'happyworm/jplayer' => array(
            'pretty_version' => '2.9.x-dev',
            'version' => '2.9.9999999.9999999-dev',
            'reference' => '4eb52eca89d27fd2a6c714bffa7927b2bd7fba4a',
            'type' => 'component',
            'install_path' => __DIR__ . '/../happyworm/jplayer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hendrismit/bootstrap-lightbox' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hendrismit/bootstrap-lightbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/collections' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => '0168d0e44ea0c4fe5451fe08cde7049b9e9f9741',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/conditionable' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => 'bea24daa0fa84b7e7b0d5b84f62c71b7e2dc3364',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/conditionable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/container' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => '1641dda2d0750b68bb1264a3b37ff3973f2e6265',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => '44f65d723b13823baa02ff69751a5948bde60c22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/database' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => 'a2d8423c05ef70101b675d4552bd7bb36a6cc890',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/database',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/macroable' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => 'e3bfaf6401742a9c6abca61b9b10e998e5b6449a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/macroable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/support' => array(
            'pretty_version' => '9.x-dev',
            'version' => '9.9999999.9999999.9999999-dev',
            'reference' => '5c38d755c5fa767d5b689867888ee4e5f53fc8a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/support',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'james-heinrich/getid3' => array(
            'pretty_version' => '2.0.x-dev',
            'version' => '2.0.9999999.9999999-dev',
            'reference' => '4e7aca96e7f4cf5ce6e08bca998334f567259965',
            'type' => 'library',
            'install_path' => __DIR__ . '/../james-heinrich/getid3',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'james-heinrich/phpthumb' => array(
            'pretty_version' => 'v1.7.20',
            'version' => '1.7.20.0',
            'reference' => '6c642aad3fa33ce88fe1307feaa6316edfc9ed76',
            'type' => 'library',
            'install_path' => __DIR__ . '/../james-heinrich/phpthumb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jasongrimes/paginator' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '3411e3cd0c6479a0b514f26e4358f0273552f221',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasongrimes/paginator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeresig/jquery.hotkeys' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeresig/jquery.hotkeys',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'johnkpaul/jquery-ajax-retry' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../johnkpaul/jquery-ajax-retry',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kriswallsmith/assetic' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '8ab3638325af9cd144242765494a9dc9b53ab430',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kriswallsmith/assetic',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ksubileau/color-thief-php' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'a1378533433dae824c2e5b70359f8b6ae16b1deb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ksubileau/color-thief-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'ee5a83310c6014b6cc07ac0610ec9d67ba452664',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(
                0 => '0.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'mmp/mmp' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'eb11124225b43866dc035f0d3795d7446ece28b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mmp/mmp',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mouse0270/bootstrap-notify' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mouse0270/bootstrap-notify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '1aec3f8d66ea86c3c9bb4ed0f6b31b156cfc1288',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(
                0 => '2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'neutron/sphinxsearch-api' => array(
            'pretty_version' => '2.0.8.1',
            'version' => '2.0.8.1',
            'reference' => 'a18fd84951ea1fb006387e2d099d025235b14d34',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neutron/sphinxsearch-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nicolasbize/faviconx' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '90900f7f06bdd3832ff252850801aebb8e8d7c5a',
            'type' => 'component',
            'install_path' => __DIR__ . '/../nicolasbize/faviconx',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/fast-route' => array(
            'pretty_version' => 'v1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '4012884e0b916e1bd895a5061d4abc3c99e283a4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/fast-route',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'othmar52/clean-rename' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../othmar52/clean-rename',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'othmar52/xwax-1.5-osc' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../othmar52/xwax-1.5-osc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '2d280c2aaa23a120f35d55cfde8581954a8e77fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => 'd47bd60659fa7ce58f4a7ec3ea959c05326ef7fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'respect/validation' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '45d109fc830644fecc1145200d6351ce4f2769d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../respect/validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ricbra/php-discogs-api' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '9e7d3484b7f66b0abd39837e815e8c976e76b69c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ricbra/php-discogs-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'robloach/component-installer' => array(
            'pretty_version' => '0.0.12',
            'version' => '0.0.12.0',
            'reference' => '1864f25db21fc173e02a359f646acd596c1b0460',
            'type' => 'composer-installer',
            'install_path' => __DIR__ . '/../robloach/component-installer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rstacruz/nprogress' => array(
            'pretty_version' => 'master',
            'version' => 'dev-master',
            'reference' => 'origin/master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rstacruz/nprogress',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'slim/csrf' => array(
            'pretty_version' => '0.8.3',
            'version' => '0.8.3.0',
            'reference' => '5f2bcf5d89adf86dc0455a32bea84d912ab466a7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/csrf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'slim/flash' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => '3c9a26b3163820acc48080336c504d0a3cac6f30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/flash',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'slim/slim' => array(
            'pretty_version' => '3.x-dev',
            'version' => '3.9999999.9999999.9999999-dev',
            'reference' => 'ce3cb65a06325fc9fe3d0223f2ae23113a767304',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/slim',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'slim/twig-view' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => '47bd5cc1cbbdf5196d0873ece0ee97c6c7b352e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/twig-view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => '6.0.x-dev',
            'version' => '6.0.9999999.9999999-dev',
            'reference' => 'c3ebc83d031b71c39da318ca8b7a07ecc67507ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'reference' => 'c30dd04b9a303689a26d7986f7cffce04203a107',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '875e90aeea2777b6f135677f618529449334a612',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'f9c7affe77a00ae32ca127ca6833d034e6d33f25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => '1a3d2ddc2c06df23e8c13ea99148bae2b8cebd35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => '6.0.x-dev',
            'version' => '6.0.9999999.9999999-dev',
            'reference' => 'd9e72497367c23e08bf94176d2be45b00a9d232a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => '6.0.x-dev',
            'version' => '6.0.9999999.9999999-dev',
            'reference' => '9c24b3fdbbe9fb2ef3a6afd8bbaadfd72dad681f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'reference' => '1ee93693c9ce25bf65799dd36224ce9293896ee1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3|3.0',
            ),
        ),
        'twbs/bootstrap' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'reference' => '68b0d231a13201eb14acd3dc84e51543d16e5f7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twbs/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '0887422319889e442458e48e2f3d9add1a172ad5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twitter/bootstrap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.1',
            ),
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'b56450eed252f6801410d810c8e1727224ae0743',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webfontkit/open-sans' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '00ab31e690edfd0d88f9ffbcd998cf298b9687e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webfontkit/open-sans',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
