#!/usr/bin/env php
<?php
/* Copyright (C) 2015-2016 othmar52 <othmar52@users.noreply.github.com>
 *
 * This file is part of sliMpd - a php based mpd web client
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/* TODO: currently there is no check of any update status
 * TODO: remove dead items after update
 * TODO: move memory_limit - value to config
 */
 
 // make sure the script es executed via php-cli
if(PHP_SAPI !== 'cli') {
    header('HTTP/1.0 403 Forbidden');
    echo "Sorry, execution is not allowed via http...\n";
    exit;
}


ini_set('max_execution_time', 0);
ini_set('memory_limit', '4096M');    // TODO: move to config

ob_start();

define('DS', DIRECTORY_SEPARATOR);
define('APP_ROOT', __DIR__ . DS);
define('APP_DEFAULT_CHARSET', 'UTF-8');

// register autoloader
require_once APP_ROOT . 'core' . DS . 'vendor-dist' . DS . 'autoload.php';

// include some additional files
foreach([
    'Utilities' . DS . 'GeneralUtility.php',
    'Utilities' . DS . 'StringUtility.php',
    'Utilities' . DS . 'SphinxUtility.php'] as $filePath) {
    require_once APP_ROOT . 'core' . DS . 'php' . DS . $filePath;
}

// set directory to root
chdir(dirname(__DIR__)); 

date_default_timezone_set('Europe/Vienna');    // TODO: move to config

session_start();

// convert all the command line arguments into a URL
$argv = $GLOBALS['argv'];
array_shift($GLOBALS['argv']);
$pathInfo = '/' . implode('/', $argv);

// Create app
$app = new \Slim\App(
    [
        'environment' => \Slim\Http\Environment::mock(['REQUEST_URI' => '/' . $pathInfo]),
        'debug' => FALSE,
        'settings' => [
            'addContentLengthHeader' => false,
            'outputBuffering' => false
        ]
    ]
);

// Set up dependencies
require APP_ROOT . 'core/php/dependencies.php';

// Register routes
require APP_ROOT . 'core/php/routes-cli.php';

$app->run();
